create extension if not exists pgcrypto;
create table if not exists public.admin_users (id uuid primary key references auth.users(id) on delete cascade,email text not null unique,created_at timestamptz not null default now());
create table if not exists public.site_content (key text primary key,data jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now());
create table if not exists public.weekly_services (id uuid primary key default gen_random_uuid(),sort_order integer not null default 0,day_en text not null,day_ta text not null default '',title_en text not null,title_ta text not null default '',time_en text not null default '',time_ta text not null default '',note_en text not null default '',note_ta text not null default '',enabled boolean not null default true);
create table if not exists public.events (id uuid primary key default gen_random_uuid(),date_en text not null default '',date_ta text not null default '',title_en text not null,title_ta text not null default '',time_en text not null default '',time_ta text not null default '',description_en text not null default '',description_ta text not null default '',image_url text,enabled boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.gallery (id uuid primary key default gen_random_uuid(),title_en text not null default '',title_ta text not null default '',image_url text not null,created_at timestamptz not null default now());
create table if not exists public.sermons (id uuid primary key default gen_random_uuid(),title_en text not null,title_ta text not null default '',description_en text not null default '',description_ta text not null default '',youtube_url text,date_en text not null default '',date_ta text not null default '',created_at timestamptz not null default now());
create table if not exists public.announcements (id uuid primary key default gen_random_uuid(),title_en text not null,title_ta text not null default '',body_en text not null default '',body_ta text not null default '',date_en text not null default '',date_ta text not null default '',enabled boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.prayer_requests (id uuid primary key default gen_random_uuid(),name text not null,phone text not null default '',request text not null,status text not null default 'new' check(status in ('new','prayed','archived')),created_at timestamptz not null default now());

alter table public.admin_users enable row level security; alter table public.site_content enable row level security; alter table public.weekly_services enable row level security; alter table public.events enable row level security; alter table public.gallery enable row level security; alter table public.sermons enable row level security; alter table public.announcements enable row level security; alter table public.prayer_requests enable row level security;
create policy "admin users own row" on public.admin_users for select to authenticated using(id=auth.uid());
create policy "users can register themselves" on public.admin_users for insert to authenticated with check(id=auth.uid());
create policy "public reads site content" on public.site_content for select to anon,authenticated using(true);
create policy "public reads services" on public.weekly_services for select to anon,authenticated using(enabled=true);
create policy "public reads events" on public.events for select to anon,authenticated using(enabled=true);
create policy "public reads gallery" on public.gallery for select to anon,authenticated using(true);
create policy "public reads sermons" on public.sermons for select to anon,authenticated using(true);
create policy "public reads announcements" on public.announcements for select to anon,authenticated using(enabled=true);
create policy "admins manage site content" on public.site_content for all to authenticated using(exists(select 1 from public.admin_users a where a.id=auth.uid())) with check(exists(select 1 from public.admin_users a where a.id=auth.uid()));
create policy "admins manage services" on public.weekly_services for all to authenticated using(exists(select 1 from public.admin_users a where a.id=auth.uid())) with check(exists(select 1 from public.admin_users a where a.id=auth.uid()));
create policy "admins manage events" on public.events for all to authenticated using(exists(select 1 from public.admin_users a where a.id=auth.uid())) with check(exists(select 1 from public.admin_users a where a.id=auth.uid()));
create policy "admins manage gallery" on public.gallery for all to authenticated using(exists(select 1 from public.admin_users a where a.id=auth.uid())) with check(exists(select 1 from public.admin_users a where a.id=auth.uid()));
create policy "admins manage sermons" on public.sermons for all to authenticated using(exists(select 1 from public.admin_users a where a.id=auth.uid())) with check(exists(select 1 from public.admin_users a where a.id=auth.uid()));
create policy "admins manage announcements" on public.announcements for all to authenticated using(exists(select 1 from public.admin_users a where a.id=auth.uid())) with check(exists(select 1 from public.admin_users a where a.id=auth.uid()));
create policy "public submits prayer requests" on public.prayer_requests for insert to anon,authenticated with check(length(trim(name))>0 and length(trim(request))>0);
create policy "admins manage prayer requests" on public.prayer_requests for all to authenticated using(exists(select 1 from public.admin_users a where a.id=auth.uid())) with check(exists(select 1 from public.admin_users a where a.id=auth.uid()));
insert into storage.buckets(id,name,public) values('church-images','church-images',true) on conflict(id) do update set public=true;
create policy "public views church images" on storage.objects for select to anon,authenticated using(bucket_id='church-images');
create policy "admins upload church images" on storage.objects for insert to authenticated with check(bucket_id='church-images' and exists(select 1 from public.admin_users a where a.id=auth.uid()));
create policy "admins update church images" on storage.objects for update to authenticated using(bucket_id='church-images' and exists(select 1 from public.admin_users a where a.id=auth.uid())) with check(bucket_id='church-images' and exists(select 1 from public.admin_users a where a.id=auth.uid()));
create policy "admins delete church images" on storage.objects for delete to authenticated using(bucket_id='church-images' and exists(select 1 from public.admin_users a where a.id=auth.uid()));

insert into public.site_content(key,data) values
('settings','{"churchNameEn":"CSI Holy Redeemer Church","churchNameTa":"சி.எஸ்.ஐ பரிசுத்த மீட்பர் ஆலயம்","placeEn":"V.V.R Nagar, Sayalgudi","placeTa":"வி.வி.ஆர். நகர், சாயல்குடி","addressEn":"VVR Nagar, Sayalgudi, Tamil Nadu 623120","addressTa":"வி.வி.ஆர். நகர், சாயல்குடி, தமிழ்நாடு 623120","phone":"7010144926","whatsapp":"7010144926","mapsUrl":"https://maps.app.goo.gl/Yq3tobrmqfw6vrWg7"}'),
('home','{"eyebrowEn":"CHURCH OF SOUTH INDIA · CSI","eyebrowTa":"சர்ச் ஆஃப் சவுத் இந்தியா · CSI","titleEn":"A place to worship, pray, serve & belong.","titleTa":"பரிசுத்த மீட்பர் ஆலயம்","subtitleEn":"Welcome to CSI Holy Redeemer Church, V.V.R Nagar, Sayalgudi — a church family growing together in faith, prayer, fellowship and the love of Christ.","subtitleTa":"சி.எஸ்.ஐ பரிசுத்த மீட்பர் ஆலயம், வி.வி.ஆர். நகர், சாயல்குடி. விசுவாசம், ஜெபம், ஐக்கியம் மற்றும் கிறிஸ்துவின் அன்பில் ஒன்றுகூடும் திருச்சபை.","heroImage":"/images/church-02.png","verseEn":"That they all may be one.","verseTa":"அவர்கள் அனைவரும் ஒன்றாயிருக்க வேண்டும்.","verseRefEn":"John 17:21","verseRefTa":"யோவான் 17:21"}'),
('about','{"kickerEn":"OUR CHURCH","kickerTa":"எங்கள் திருச்சபை","titleEn":"Growing together in faith and fellowship.","titleTa":"விசுவாசத்திலும் ஐக்கியத்திலும் ஒன்றாக.","body1En":"CSI Holy Redeemer Church is part of the Church of South India and serves the V.V.R Nagar community in Sayalgudi through worship, prayer, God''s Word and fellowship.","body1Ta":"சி.எஸ்.ஐ பரிசுத்த மீட்பர் ஆலயம், சர்ச் ஆஃப் சவுத் இந்தியாவின் ஒரு பகுதியாக, சாயல்குடி வி.வி.ஆர். நகர் மற்றும் சுற்றுப்புற மக்களுக்கு ஆராதனை, ஜெபம், தேவனுடைய வார்த்தை மற்றும் ஐக்கியத்தின் மூலம் சேவை செய்கிறது.","body2En":"Children, young people, families and people of all ages are warmly welcomed into our church family.","body2Ta":"எங்கள் திருச்சபை குடும்பத்தில் குழந்தைகள், இளைஞர்கள், குடும்பங்கள் மற்றும் அனைத்து வயதினரும் அன்புடன் வரவேற்கப்படுகிறார்கள்.","image":"/images/church-02.png","verseEn":"That they all may be one.","verseTa":"அவர்கள் அனைவரும் ஒன்றாயிருக்க வேண்டும்.","verseRefEn":"John 17:21","verseRefTa":"யோவான் 17:21"}'),
('worship','{"kickerEn":"REGULAR GATHERINGS","kickerTa":"ஒழுங்கான கூட்டங்கள்","titleEn":"A rhythm of prayer throughout the week.","titleTa":"ஒவ்வொரு வாரமும் ஒன்றாக ஜெபிப்போம்.","bodyEn":"Our weekly rhythm creates dedicated times for youth, women and the whole church family to pray, fellowship and seek God together.","bodyTa":"இளைஞர்கள், பெண்கள் மற்றும் முழு சபை குடும்பத்திற்கான தனித்தனி ஜெப ஐக்கியங்களுடன், வாரத்தின் ஒவ்வொரு நாளும் தேவனைத் தேடும் வாய்ப்பு உள்ளது."}'),
('pastor','{"name":"Rev. D. Duraisingh","nameTa":"ரெவ. டி. துரைசிங்","bioEn":"The pastor’s welcome message, photograph and ministry information can be managed here.","bioTa":"ஆயரின் வரவேற்புச் செய்தி, புகைப்படம் மற்றும் ஊழியத் தகவல்களை இங்கே நிர்வகிக்கலாம்.","photo":""}'),
('prayer','{"titleEn":"Share your prayer request.","titleTa":"உங்கள் ஜெபக் கோரிக்கையை பகிருங்கள்.","bodyEn":"Your request will be sent to the church prayer team. We will pray for you.","bodyTa":"உங்கள் கோரிக்கை திருச்சபை ஜெபக் குழுவிற்கு அனுப்பப்படும். நாங்கள் உங்களுக்காக ஜெபிக்கிறோம்."}'),
('contact','{"kickerEn":"VISIT US","kickerTa":"எங்களைச் சந்தியுங்கள்","titleEn":"Come worship with us.","titleTa":"ஆராதிக்க வாருங்கள்.","bodyEn":"We would be glad to welcome you for worship, prayer and fellowship.","bodyTa":"ஆராதனை, ஜெபம் மற்றும் ஐக்கியத்திற்காக உங்களை அன்புடன் வரவேற்கிறோம்."}'),
('sections','{"about":true,"schedule":true,"events":true,"gallery":true,"sermons":true,"pastor":true,"prayer":true,"contact":true}') on conflict(key) do nothing;
insert into public.weekly_services(sort_order,day_en,day_ta,title_en,title_ta,time_en,time_ta,note_en,note_ta) values
(1,'Sunday','ஞாயிற்றுக்கிழமை','Sunday Worship Service','ஞாயிறு ஆராதனை','9:00 AM – 11:30 AM','காலை 9:00 – 11:30','First Sunday: Holy Communion Service','முதல் ஞாயிறு: பரிசுத்த திருவிருந்து ஆராதனை'),
(2,'Monday','திங்கட்கிழமை','Youth Boys Prayer Fellowship','வாலிபர் சகோதரர்கள் ஜெப ஐக்கியம்','7:00 PM – 9:00 PM','மாலை 7:00 – 9:00','Weekly prayer and fellowship','வாராந்திர ஜெபமும் ஐக்கியமும்'),
(3,'Tuesday','செவ்வாய்க்கிழமை','Youth Girls Prayer Fellowship','வாலிப சகோதரிகள் ஜெப ஐக்கியம்','7:00 PM – 9:00 PM','மாலை 7:00 – 9:00','Weekly prayer and fellowship','வாராந்திர ஜெபமும் ஐக்கியமும்'),
(4,'Wednesday','புதன்கிழமை','Women''s Fellowship Prayer','பெண்கள் ஐக்கிய ஜெபம்','7:00 PM – 9:00 PM','மாலை 7:00 – 9:00','Women’s fellowship and prayer','பெண்கள் ஐக்கியமும் ஜெபமும்'),
(5,'Thursday','வியாழக்கிழமை','Common Prayer Service','பொது ஜெப ஆராதனை','7:00 PM – 9:00 PM','மாலை 7:00 – 9:00','Church-wide prayer service','சபை முழுவதற்குமான பொது ஜெப ஆராதனை'),
(6,'Friday','வெள்ளிக்கிழமை','Litany Prayer','லித்தானியா ஜெபம்','7:00 PM – 9:00 PM','மாலை 7:00 – 9:00','Weekly litany prayer','வாராந்திர லித்தானியா ஜெபம்'),
(7,'1st Saturday','முதல் சனிக்கிழமை','Monthly Fasting Prayer','மாதாந்திர உபவாச ஜெபம்','10:00 AM – 2:00 PM','காலை 10:00 – பிற்பகல் 2:00','Every first Saturday of the month','ஒவ்வொரு மாதமும் முதல் சனிக்கிழமை');
insert into public.events(date_en,date_ta,title_en,title_ta,time_en,time_ta,description_en,description_ta) values
('Every 1st Saturday','ஒவ்வொரு முதல் சனிக்கிழமையும்','Monthly Fasting Prayer','மாதாந்திர உபவாச ஜெபம்','10:00 AM – 2:00 PM','காலை 10:00 – பிற்பகல் 2:00','A monthly time of fasting, prayer and seeking God together.','ஒவ்வொரு மாதமும் ஒன்றாக உபவாசித்து, ஜெபித்து, தேவனைத் தேடும் நேரம்.'),
('Special','சிறப்பு','Functions & Special Prayers','சபை நிகழ்வுகள் மற்றும் சிறப்பு ஜெபங்கள்','Admin will update','நிர்வாகி புதுப்பிப்பார்','Church functions, special prayer meetings and celebrations can be published from the admin dashboard.','சபை நிகழ்வுகள், சிறப்பு ஜெபக் கூட்டங்கள் மற்றும் கொண்டாட்டங்களை நிர்வாகி கட்டுப்பாட்டகத்தில் இருந்து வெளியிடலாம்.');
insert into public.gallery(title_en,title_ta,image_url) values
('Church tower','தேவாலயக் கோபுரம்','/images/church-02.png'),('Church exterior','தேவாலயத்தின் வெளிப்புறம்','/images/church-04.png'),('Church tower view','தேவாலயக் கோபுரத் தோற்றம்','/images/church-03.png'),('Church tower','தேவாலயக் கோபுரம்','/images/church-01.png'),('Sanctuary','தேவாலயத்தின் உள்ளரங்கம்','/images/church-05.png'),('Church fellowship','சபை ஐக்கியம்','/images/event-wide.png'),('Church gathering','சபை ஒன்று கூடல்','/images/event-01.png'),('Church celebration','சபை கொண்டாட்டம்','/images/event-02.png');
-- After creating an Auth user, run: insert into public.admin_users(id,email) values ('AUTH-USER-UUID-HERE','pastor@example.com');
